# Generated by Django 5.2.4 on 2025-07-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_timestamp_fields"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["-date_joined"], name="accounts_cu_date_jo_36131c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["user_type"], name="accounts_cu_user_ty_97b0bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_active"], name="accounts_cu_is_acti_2885e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="accounts_cu_email_5ce40b_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["username"], name="accounts_cu_usernam_ab560e_idx"
            ),
        ),
    ]
