# Generated by Django 5.2.4 on 2025-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="test",
            field=models.BooleanField(default=False),
        ),
    ]
