# Generated by Django 5.2.4 on 2025-07-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="test",
        ),
    ]
