# Generated by Django 5.2.4 on 2025-07-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_test"),
    ]

    operations = []
