# Generated by Django 5.2.4 on 2025-07-08 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(
                fields=["-created_at"], name="inquiries_i_created_2b1632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["status"], name="inquiries_i_status_8fae14_idx"),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["client"], name="inquiries_i_client_a05205_idx"),
        ),
    ]
